Update mocha config to handle ESM
Now `npm run tests` starts the tests but sinon is unhappy because of

  1) "before all" hook: beforeAll in "{root}":
     TypeError: ES Modules cannot be stubbed
      at Function.stub (file:///home/afabre/dev/api.statox.fr/node_modules/sinon/pkg/sinon-esm.js:3956:15)
      at Sandbox.stub (file:///home/afabre/dev/api.statox.fr/node_modules/sinon/pkg/sinon-esm.js:3435:39)
      at setupFakeAuth (tests/helpers/auth/index.ts:12:10)
      at Context.beforeAll (tests/helpers/mocha/routesMochaWrapper.ts:13:13)